# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  push:
    branches: 
      - 'release'
  pull_request:
    branches: 
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout source code
          uses: actions/checkout@v2

        - name: Cache node modules
          uses: actions/cache@v2
          with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-node-
                      
        - name: Install Dependencies
          run: npm ci
          
        - name: Generate Environment Variable Files for Production
          run: /
            echo "VITE_SERVER_URL=$VITE_SERVER_URL" >> .env.production
          env:
            VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

        - name: Build
          run: npm run build 
 
        - name: Deploy
          env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

          run: |
              aws s3 cp \
              --recursive \
              --region ap-northeast-2 \
              build s3://cupick.co
              
        - name: Invalidate CloudFront Cache
          run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
